# raxmlng.sub
# Submissão de RaxML-NG via Condor

executable              = /usr/bin/raxml-ng
arguments               = --threads 4 --force perf_threads -msa infile.fas --workers 4 --bs-trees autoMRE{1000} --seed 12345 --all --prefix result --model GTR+G

log                     = raxmlng.log
output                  = raxmlng.out
error                   = raxmlng.err

should_transfer_files   = NO

request_cpus            = 4
request_memory          = 2G
request_disk            = 2G

queue